global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fieldops-api'
    static_configs:
      - targets: ['host.docker.internal:5001']  # .NET API metrics endpoint
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'fieldops-web'
    static_configs:
      - targets: ['host.docker.internal:5002']  # Blazor WASM metrics if any
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 5s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 5s
